modLoader="javafml"
loaderVersion="[40,)"
license="All Rights Reserved"

[[mods]]
modId="mks_tech"
version="0.2.0"
displayName="MKS tech"
credits="Mod created by Ssprt_ with using mod maker MCreator"
displayURL="http://ssprtcomm.tilda.ws"
logoFile="logo.png"
authors="Ssprt_ MCreator"
description='''
MKS tech this is a mod that adds electronics to our favorite Minecraft, some of them have functionality
'''

[[dependencies.mks_tech]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




